image: python:3.6
stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  KOZLEK_REGISTRY: registry.kozlek.net
  DOCKER_IMAGE: $KOZLEK_REGISTRY/surirobot/api-emotions

cache:
  paths:
    - .cache/
    - venv/

test_dev:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest --cov=api
  except:
    - master

test_master:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest --cov=api -m ''
  only:
    - master

test_externalapi:
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest -m externalapi
  only:
    - schedules

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $KOZLEK_REGISTRY
  script:
    - docker build -t DOCKER_IMAGE:latest .
    - docker run -e MICROSOFT_API_KEY=$MICROSOFT_API_KEY --entrypoint pytest $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - master
    - staging
  tags:
    - docker
